package main.java;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'SYSTEM' at '3/19/17 12:13 AM' with Gradle 3.1
 *
 * @author SYSTEM, @date 3/19/17 12:13 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
