package test.java;

import org.junit.Test;

import main.java.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'SYSTEM' at '3/19/17 12:13 AM' with Gradle 3.1
 *
 * @author SYSTEM, @date 3/19/17 12:13 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
